### PR TITLE
Added support for using variables

### PR DESCRIPTION
**Pull request by roby-rodriguez**
checkout the updated readme

### CODE REVIEW

**Comment by mlegenhausen** [comment]
Why do you not simply provide a function to generate your constants definition?

```js
{
  constants: function () {
     var var1 = 1;
     var var2 = 2;
     return {
        var1: var1,
        var2: var2,
        var3: var1 + var2
     };
  }
}
```

This pull request seems a little bit overpowered. Do you have any usecases where this approuch works better than the current implementation?

BTW: You kill most of the contents in the readme.

**Comment by roby-rodriguez** [comment]
Sorry about the readme. I'm new to Github/JavaScript development. I guess my approach is a bit of an overkill, but can you achieve this output with the standard approach:

```js
angular.module("exampleApp",[])

.constant('RESOURCES', (function() {
  var resource = 'http://127.0.0.1:8008';
  return {
    USERS_DOMAIN: resource,
    USERS_API: resource + '/users',
    BASIC_INFO: resource + '/api/info'
  }
})());
```
Such that I can then use the RESOURCE object like this in my Angular code:
```js
myApp.controller("ExampleCtrl", function(RESOURCES){
  $scope.domain = RESOURCES.USERS_DOMAIN;
});
```
I've tried out your function but it generates something like:
```js
"use strict";
angular.module('app', [])
.constant('apiEndpoint', 'https://localhost')
.constant('categoriesUrl', 'https://localhost/categories')
.constant('productsUrl', 'https://localhost/products');
```

Maybe I'm missing something so could you please tell me how could I obtain a single object that contains all these fields?

**Comment by mlegenhausen** [comment]
Try out this:

```js
{
  constants: function () {
    var resource = 'http://127.0.0.1:8008';
    return {
      RESOURCES: {
        USERS_DOMAIN: resource,
        USERS_API: resource + '/users',
        BASIC_INFO: resource + '/api/info'
      };
    }
  }
}
```

Or you can split up this stuff e. g.

```js
// config/resources.js
var resource = 'http://127.0.0.1:8008';
module.exports = {
  USERS_DOMAIN: resource,
  USERS_API: resource + '/users',
  BASIC_INFO: resource + '/api/info'
};
```

And then simply require.

```js
// Gruntfile.js
{
  constants: function () {
    return {
      RESOURCES: require('./config/resources')
    };
  }
}
```

I hope this helps.

**Comment by roby-rodriguez** [comment]
It works like a charm. Thanks for the tip. I'll be closing the pull request.

**Pull request closed without merging**
