### PR TITLE
Add use strict to template

### PR DESCRIPTION
**Pull request by tlvince**

### CODE REVIEW

**Comment by ajoslin103** [comment]
it writes "use strict"; with double quotes - which jshint fails

**Comment by mlegenhausen** [comment]
For  a work around you can copy the template and create your own strict version.

**Comment by ajoslin103** [comment]
I have tried to put a clean before jshint and write the config after jshint runs, but that doesn't always work

thanks, I'll do as you suggest

**Comment by mlegenhausen** [comment]
The current problem is that, we have `use strict` in the default wrapper. When we add it to the normal template we have it double. I think removing it from the default wrapper and add a new option for adding a `use strict` parameter is the right solution.

Closed for now.

**Pull request closed without merging**
